name: Build Jasypt-Go Package

on:
  workflow_dispatch:
  release:
    types: [released]
  push:
    branches:
      - master
    paths:
      - '**/github.com/alice52/jasypt-go/**'
      - '.github/workflows/build-jasypt-go.yml'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
        go: ['1.18.x', '1.19.x', '1.20.x', '1.21.x']
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      PROJECT_PREFIX: github.com/alice52
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build Jasypt-Go Package
        run: |
          PROJECT_NAME=jasypt-go
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME
          go build ./...
          go test ./...

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.os }}-${{ matrix.go }}-Jasypt-Go
#          path: ${{ github.workspace }}/**/Jasypt-Go
#          retention-days: 1
